CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS embeddings (
  id int GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  embedding VECTOR(768) NOT NULL,
  lesson TEXT NOT NULL,
  section TEXT NOT NULL,
  content TEXT NOT NULL
);